# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.6

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/chris/gaia/gaia

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/chris/gaia/gaia

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chris/gaia/gaia/CMakeFiles /home/chris/gaia/gaia/CMakeFiles/progress.make
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chris/gaia/gaia/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gaia

# Build rule for target.
gaia: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gaia
.PHONY : gaia

# fast build rule for target.
gaia/fast:
	$(MAKE) -f CMakeFiles/gaia.dir/build.make CMakeFiles/gaia.dir/build
.PHONY : gaia/fast

Crust.o: Crust.cpp.o
.PHONY : Crust.o

# target to build an object file
Crust.cpp.o:
	$(MAKE) -f CMakeFiles/gaia.dir/build.make CMakeFiles/gaia.dir/Crust.cpp.o
.PHONY : Crust.cpp.o

Crust.i: Crust.cpp.i
.PHONY : Crust.i

# target to preprocess a source file
Crust.cpp.i:
	$(MAKE) -f CMakeFiles/gaia.dir/build.make CMakeFiles/gaia.dir/Crust.cpp.i
.PHONY : Crust.cpp.i

Crust.s: Crust.cpp.s
.PHONY : Crust.s

# target to generate assembly for a file
Crust.cpp.s:
	$(MAKE) -f CMakeFiles/gaia.dir/build.make CMakeFiles/gaia.dir/Crust.cpp.s
.PHONY : Crust.cpp.s

InnerCore.o: InnerCore.cpp.o
.PHONY : InnerCore.o

# target to build an object file
InnerCore.cpp.o:
	$(MAKE) -f CMakeFiles/gaia.dir/build.make CMakeFiles/gaia.dir/InnerCore.cpp.o
.PHONY : InnerCore.cpp.o

InnerCore.i: InnerCore.cpp.i
.PHONY : InnerCore.i

# target to preprocess a source file
InnerCore.cpp.i:
	$(MAKE) -f CMakeFiles/gaia.dir/build.make CMakeFiles/gaia.dir/InnerCore.cpp.i
.PHONY : InnerCore.cpp.i

InnerCore.s: InnerCore.cpp.s
.PHONY : InnerCore.s

# target to generate assembly for a file
InnerCore.cpp.s:
	$(MAKE) -f CMakeFiles/gaia.dir/build.make CMakeFiles/gaia.dir/InnerCore.cpp.s
.PHONY : InnerCore.cpp.s

Mantle.o: Mantle.cpp.o
.PHONY : Mantle.o

# target to build an object file
Mantle.cpp.o:
	$(MAKE) -f CMakeFiles/gaia.dir/build.make CMakeFiles/gaia.dir/Mantle.cpp.o
.PHONY : Mantle.cpp.o

Mantle.i: Mantle.cpp.i
.PHONY : Mantle.i

# target to preprocess a source file
Mantle.cpp.i:
	$(MAKE) -f CMakeFiles/gaia.dir/build.make CMakeFiles/gaia.dir/Mantle.cpp.i
.PHONY : Mantle.cpp.i

Mantle.s: Mantle.cpp.s
.PHONY : Mantle.s

# target to generate assembly for a file
Mantle.cpp.s:
	$(MAKE) -f CMakeFiles/gaia.dir/build.make CMakeFiles/gaia.dir/Mantle.cpp.s
.PHONY : Mantle.cpp.s

OuterCore.o: OuterCore.cpp.o
.PHONY : OuterCore.o

# target to build an object file
OuterCore.cpp.o:
	$(MAKE) -f CMakeFiles/gaia.dir/build.make CMakeFiles/gaia.dir/OuterCore.cpp.o
.PHONY : OuterCore.cpp.o

OuterCore.i: OuterCore.cpp.i
.PHONY : OuterCore.i

# target to preprocess a source file
OuterCore.cpp.i:
	$(MAKE) -f CMakeFiles/gaia.dir/build.make CMakeFiles/gaia.dir/OuterCore.cpp.i
.PHONY : OuterCore.cpp.i

OuterCore.s: OuterCore.cpp.s
.PHONY : OuterCore.s

# target to generate assembly for a file
OuterCore.cpp.s:
	$(MAKE) -f CMakeFiles/gaia.dir/build.make CMakeFiles/gaia.dir/OuterCore.cpp.s
.PHONY : OuterCore.cpp.s

Simulation.o: Simulation.cpp.o
.PHONY : Simulation.o

# target to build an object file
Simulation.cpp.o:
	$(MAKE) -f CMakeFiles/gaia.dir/build.make CMakeFiles/gaia.dir/Simulation.cpp.o
.PHONY : Simulation.cpp.o

Simulation.i: Simulation.cpp.i
.PHONY : Simulation.i

# target to preprocess a source file
Simulation.cpp.i:
	$(MAKE) -f CMakeFiles/gaia.dir/build.make CMakeFiles/gaia.dir/Simulation.cpp.i
.PHONY : Simulation.cpp.i

Simulation.s: Simulation.cpp.s
.PHONY : Simulation.s

# target to generate assembly for a file
Simulation.cpp.s:
	$(MAKE) -f CMakeFiles/gaia.dir/build.make CMakeFiles/gaia.dir/Simulation.cpp.s
.PHONY : Simulation.cpp.s

Thermosphere.o: Thermosphere.cpp.o
.PHONY : Thermosphere.o

# target to build an object file
Thermosphere.cpp.o:
	$(MAKE) -f CMakeFiles/gaia.dir/build.make CMakeFiles/gaia.dir/Thermosphere.cpp.o
.PHONY : Thermosphere.cpp.o

Thermosphere.i: Thermosphere.cpp.i
.PHONY : Thermosphere.i

# target to preprocess a source file
Thermosphere.cpp.i:
	$(MAKE) -f CMakeFiles/gaia.dir/build.make CMakeFiles/gaia.dir/Thermosphere.cpp.i
.PHONY : Thermosphere.cpp.i

Thermosphere.s: Thermosphere.cpp.s
.PHONY : Thermosphere.s

# target to generate assembly for a file
Thermosphere.cpp.s:
	$(MAKE) -f CMakeFiles/gaia.dir/build.make CMakeFiles/gaia.dir/Thermosphere.cpp.s
.PHONY : Thermosphere.cpp.s

Tile.o: Tile.cpp.o
.PHONY : Tile.o

# target to build an object file
Tile.cpp.o:
	$(MAKE) -f CMakeFiles/gaia.dir/build.make CMakeFiles/gaia.dir/Tile.cpp.o
.PHONY : Tile.cpp.o

Tile.i: Tile.cpp.i
.PHONY : Tile.i

# target to preprocess a source file
Tile.cpp.i:
	$(MAKE) -f CMakeFiles/gaia.dir/build.make CMakeFiles/gaia.dir/Tile.cpp.i
.PHONY : Tile.cpp.i

Tile.s: Tile.cpp.s
.PHONY : Tile.s

# target to generate assembly for a file
Tile.cpp.s:
	$(MAKE) -f CMakeFiles/gaia.dir/build.make CMakeFiles/gaia.dir/Tile.cpp.s
.PHONY : Tile.cpp.s

TileLayer.o: TileLayer.cpp.o
.PHONY : TileLayer.o

# target to build an object file
TileLayer.cpp.o:
	$(MAKE) -f CMakeFiles/gaia.dir/build.make CMakeFiles/gaia.dir/TileLayer.cpp.o
.PHONY : TileLayer.cpp.o

TileLayer.i: TileLayer.cpp.i
.PHONY : TileLayer.i

# target to preprocess a source file
TileLayer.cpp.i:
	$(MAKE) -f CMakeFiles/gaia.dir/build.make CMakeFiles/gaia.dir/TileLayer.cpp.i
.PHONY : TileLayer.cpp.i

TileLayer.s: TileLayer.cpp.s
.PHONY : TileLayer.s

# target to generate assembly for a file
TileLayer.cpp.s:
	$(MAKE) -f CMakeFiles/gaia.dir/build.make CMakeFiles/gaia.dir/TileLayer.cpp.s
.PHONY : TileLayer.cpp.s

Troposphere.o: Troposphere.cpp.o
.PHONY : Troposphere.o

# target to build an object file
Troposphere.cpp.o:
	$(MAKE) -f CMakeFiles/gaia.dir/build.make CMakeFiles/gaia.dir/Troposphere.cpp.o
.PHONY : Troposphere.cpp.o

Troposphere.i: Troposphere.cpp.i
.PHONY : Troposphere.i

# target to preprocess a source file
Troposphere.cpp.i:
	$(MAKE) -f CMakeFiles/gaia.dir/build.make CMakeFiles/gaia.dir/Troposphere.cpp.i
.PHONY : Troposphere.cpp.i

Troposphere.s: Troposphere.cpp.s
.PHONY : Troposphere.s

# target to generate assembly for a file
Troposphere.cpp.s:
	$(MAKE) -f CMakeFiles/gaia.dir/build.make CMakeFiles/gaia.dir/Troposphere.cpp.s
.PHONY : Troposphere.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/gaia.dir/build.make CMakeFiles/gaia.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/gaia.dir/build.make CMakeFiles/gaia.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/gaia.dir/build.make CMakeFiles/gaia.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... gaia"
	@echo "... rebuild_cache"
	@echo "... Crust.o"
	@echo "... Crust.i"
	@echo "... Crust.s"
	@echo "... InnerCore.o"
	@echo "... InnerCore.i"
	@echo "... InnerCore.s"
	@echo "... Mantle.o"
	@echo "... Mantle.i"
	@echo "... Mantle.s"
	@echo "... OuterCore.o"
	@echo "... OuterCore.i"
	@echo "... OuterCore.s"
	@echo "... Simulation.o"
	@echo "... Simulation.i"
	@echo "... Simulation.s"
	@echo "... Thermosphere.o"
	@echo "... Thermosphere.i"
	@echo "... Thermosphere.s"
	@echo "... Tile.o"
	@echo "... Tile.i"
	@echo "... Tile.s"
	@echo "... TileLayer.o"
	@echo "... TileLayer.i"
	@echo "... TileLayer.s"
	@echo "... Troposphere.o"
	@echo "... Troposphere.i"
	@echo "... Troposphere.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

